### ISSUE TITLE
Text prompt enhancement: enable arrow keys, and backspace for password inputs

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-cli#167]
1. Expected behavior and actual behavior.

2. Steps to reproduce the problem.
`nem2-cli transaction transfer`
at any input: input text, and try to go to the left to rectify the typed text
the terminal records `^[[D` at each keypress

3. Specifications like the version of the project, operating system, or hardware.
ubuntu 16.04

**Comment by dgarcia360** [comment]
Related issue: https://github.com/anseki/readline-sync/issues/22

**Comment by decentraliser** [comment]
Thanks for the pointer!
I gave a go to "read" that is mentionned in the issue, but it's not great
Will try "inquirer" that is looking strong https://www.npmjs.com/package/inquirer in the next couple of days

**Comment by dgarcia360** [comment]
Ideally, we will need to only change the ``OptionsResolver`` and ``OptionsChoiceResolver`` functions with the latest resolvers reorg. https://github.com/nemtech/nem2-cli/blob/072cb578e09488284ecd34e0b72f860ed66dbb37/src/options-resolver.ts#L21

Other promising libraries we might want to review:
- https://github.com/klaussinani/qoa
- https://github.com/terkelg/prompts

**Comment by decentraliser** [comment]
removing my assignment as I'll be busier than usual during the coming days

**Comment by NemTechCN** [comment]
@dgarcia360 I tried to enhence text prompt by replacing `readline-sync` with `prompts`. And I commited a PR about this. #174 

It seems a big change. In fact, I just rewrite the `OptionResolver`, but I need to add `async...await` to all the functions about `OptionsResolver`. And I have no idea to reduce these.

**Comment by decentraliser** [comment]
Indeed that's the difficulty about this change, the other libs seem all to
be async


I saw (but not tried) a solution that consists in using a library that
transforms async functions in sync functions

https://github.com/abbr/deasync

**Comment by mikeaustin** [comment]
For what it's worth, I was expecting readline-sync to behave somewhat line readline, in which arrow key history is a fundamental concept. To my surprise, readline-async doesn't support arrow keys?

I very much appreciate providing synchronous prompt(), but without history I guess I don't understand its use. readline arrow key history works on my Mac terminal and in PowerShell on my Windows PC. I'm just looking for simple sync input with history.
