### ISSUE TITLE
Support HD wallets

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-cli#176]
## Changes

**NOTE**: The CLI should support HD wallets and private key based wallets.

### Generate Account

``symbol-cli account generate``

Add the option:

| param | type | description | default |
| -- | -- | -- | -- | 
| --hd | flag (boolean) | Generate a  HD seed account. |  false |

### Create Profile

``symbol-cli profile create``

Add the flag:

| param | type | description | default |
| -- | -- | -- | -- | 
| --hd | flag (boolean) | Create a profile from a HD seed account. |  false |

### Import Profile 
                                
``symbol-cli profile import``

Add the option:

| param | type | description | default |
| -- | -- | -- | -- | 
| --mnemonic | string | (Optional) Import a profile with a mnemonic phrase. | |

### List profiles

``symbol-cli profile list``

The profile table should show in a new row the "Type", which can be "PrivateKey" or "HD.

### Decrypt profile
 
``symbol-cli profile decrypt``

If it's an HD profile, it should show the mnemonic + private key.

**Comment by dgarcia360** [comment]
@decentraliser Updated the spec, please do not hesitate to add your improvements 👍

**Comment by decentraliser** [comment]
I disagree to have the derivationPath as a string, it will bring to errors
I propose to stick to what we have in the others wallets, defining 10 standard paths only for child accounts

**Comment by dgarcia360** [comment]
Ok with me, 10 looks enough at the moment.

**Comment by decentraliser** [comment]
@dgarcia360 I don't get the purpose of the profile flag in the Create Profile command

**Comment by dgarcia360** [comment]
@decentraliser  I've changed it to ``derivationProfile`` so that there is no conflict with the current ``profile`` property. 

Imagine that the derivationProfile passed is the name of an HD wallet seed account already stored. You might want to derive a child account from it (derivationPath) and store this child account as a new profile to sign transactions with the CLI.

**Comment by decentraliser** [comment]
OK, makes sense, that adds a fait bit of logic tho the command, I'll think about it
