### ISSUE TITLE
/usr/bin/env: ‘node\r’ no such file or directory

### ISSUE THREAD

**Issue by meyns** [nemtech/symbol-cli#215]
1. Expected behavior and actual behavior.
After installation and trying to run nem2-cli I get this error:
/usr/bin/env: ‘node\r’ no such file or directory
Google says it has something to do with the wrong encoding of the endings in the nem2-cli file(s).

2. Steps to reproduce the problem.
Install nem2-cli and run nem2-cli

3. Specifications like the version of the project, operating system, or hardware.
Using latest version of nem2-cli and node v13.8.0

**Comment by dgarcia360** [comment]
Thanks for reporting. At this moment, the only node version supported is Node.js 12 LTS https://github.com/nemtech/nem2-cli#requirements

I leave this issue open to keep it in mind when adding support for Node.js 13.

**Comment by dgarcia360** [comment]
@meyns This issue should be solved now that we are deploying from Travis. If you experiment the same problem, do not hesitate to open the issue again.
