### ISSUE TITLE
Maxfee validator does not work

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-cli#241]
1. Expected behavior and actual behavior.
should throw when not given a valid amount

2. Steps to reproduce the problem.
![image](https://user-images.githubusercontent.com/36499647/76409324-2cd5b200-63c9-11ea-80f6-5feb32b02c6d.png)

3. Specifications like the version of the project, operating system, or hardware.
0.18.2 Win10 WSL

**Comment by dgarcia360** [comment]
Well seen, thanks for reporting!
