### ISSUE TITLE
Update block subcommand to display hash infomation

### ISSUE THREAD

**Issue by ftakao2007** [nemtech/symbol-cli#309]
Hello

Currently, although the Generation Hash is displayed by the block subcommand, Hash is not displayed.

So, I would like you to update the program as follows so that Hash is also displayed.
[updated-blocksubcommand](https://github.com/nemtech/symbol-cli/compare/master...ftakao2007:updated-blocksubcommand?expand=1)

Attached is a capture of the execution result of the program that I modified at hand.
![image](https://user-images.githubusercontent.com/3776879/87236769-1b102400-c428-11ea-8b38-9fc99aaa9a39.png)

Thank you for your cooperation.

**Comment by xembook** [comment]
I too think it would be useful to have Hash. Because I can verify the validity of the block headers.

**Comment by dgarcia360** [comment]
@ftakao2007 Thanks for reporting the issue! This has been solved in the latest CLI release (0.21.1).
