### ISSUE TITLE
cli uses cat.harvest by default

### ISSUE THREAD

**Issue by Dawn-Piper** [nemtech/symbol-cli#311]
1. Expected behavior and actual behavior.
After running a private server and setting up symbol-cli v20.1 according to documentation it was found that the symbol-cli.config.json is trying to use cat.harvest as the network currency.

This is from the end of the config.json:
`"networkCurrency":{"namespaceId":"cat.harvest","divisibility":6},"version":3,"default":"1","type":"PrivateKey"}}`

Before changing this from cat.harvest to cat.currency, no transactions could be published to chain. After changing, it worked fine.

This seems like a bug and should be fixed. The problem does not end here for us because the SDK is not getting our transactions accepted either. Is the sdk also configured to use cat.harvest? If so, how can I change it?

**Comment by dgarcia360** [comment]
@Dawn-Piper Thanks for reporting the issue. 

This is effectively a problem with how the CLI resolves the currency mosaic id. Reading the code, the first mosaic definition transaction added in the first block is taken as the currency mosaic. If the private network defines ``cat.harvest`` as the first mosaic definition transaction, then the resolution is not working as expected.

While this is not fixed, you should be able to define the currency mosaic id and divisibility manually as a workaround. Pass the options ``--namespace-id`` and ``--divisibility`` to the command. For example, to import a new profile and set ``cat.currency`` as the default currency mosaic you should add ``symbol-cli profile import --namespace-id cat.currency --divisibility 6``.

> The problem does not end here for us because the SDK is not getting our transactions accepted either. 

The SDK is not configured to use a mosaic by default. In fact, if you manage to get the transaction confirmed in the CLI, this is using the SDK underneath. I'd appreciate it if you could report the issue in the [SDK repository](https://github.com/nemtech/symbol-sdk-typescript-javascript) with the code snippet you are using to announce a transaction and any errors you get after running the code.
