### ISSUE TITLE
transaction transfer announces but never confirms

### ISSUE THREAD

**Issue by BIMTrazer** [nemtech/symbol-cli#313]
Hello everyone.

1. Expected behavior and actual behavior.
What works, creating profile/account, receive mosaics from faucet, showing account info... But when we try to send a transfer transaction: "symbol-cli transaction transfer --recipient-address TCY6OBA6VOGAOBYNMP6X2BDHODTLCBTOUHJMDBY --mosaics "@symbol.xym::10000000" --message "test message" --sync" it says "SUCCESS Transaction announced" but then it just hangs there "Processing" indefinitely.

2. Steps to reproduce the problem.
- Create account: symbol-cli account generate / symbol-cli profile create
- Receive mosaics from other account or faucet
- Execute mosaic transfer: symbol-cli transaction transfer --recipient-address TCY6OBA6VOGAOBYNMP6X2BDHODTLCBTOUHJMDBY --mosaics "@symbol.xym::10000000" --message "test message"

3. Specifications like the version of the project, operating system, or hardware.
Symbol CLI v0.21.1
Slackware Linux Current

Note: node URL: http://api-01.us-east-1.096x.symboldev.network:3000 (same as wallet and faucet)
When we send same transaction using the wallet it works perfectly

Thanks.

**Comment by dgarcia360** [comment]
Hi @BIMTrazer, thanks for reporting. I suspect the maximum fee set was too low and no node is accepting the transaction.

Could you please try by setting the [max_fee](https://nemtech.github.io/concepts/fees.html#transaction-fee) to a higher value (e.g. 2 XEM = 2000000):

`symbol-cli transaction transfer --recipient-address TCY6OBA6VOGAOBYNMP6X2BDHODTLCBTOUHJMDBY --mosaics "@symbol.xym::10000000" --message "test message" --max-fee 2000000 --sync`

**Comment by BIMTrazer** [comment]
You're right, we were not using absolute amount, sorry.

Thank you very much.
