### ISSUE TITLE
Profile List 

### ISSUE THREAD

**Issue by ivyfung1** [nemtech/symbol-cli#325]
I created a new account and saved, e.g. `SUCCESS Stored Alice profile`.
When I want to view all the accounts saved, `symbol-cli profile list`, the respond comes back `Can't retrieve the profile list.`

**Comment by meyns** [comment]
I'll add some extra information:
"profile list" does not work but "profile list --profile profile-001" does work
![image](https://user-images.githubusercontent.com/6676974/96238639-00a59380-0f9f-11eb-8f10-8a45b6c867b9.png)

**Comment by meyns** [comment]
Looks like the problem lies with the combination of old and new profiles.
I had some old profiles from previous version, and by deleting symbol-cli.config.json it works again
