### ISSUE TITLE
symbol-cli is not work [v0.22.0]

### ISSUE THREAD

**Issue by joarrries** [nemtech/symbol-cli#340]
1. Expected behavior and actual behavior.
generate account

2. Steps to reproduce the problem.
![image](https://user-images.githubusercontent.com/54062081/102866981-0b831580-4473-11eb-80d9-59d727904f13.png)

3. Specifications like the version of the project, operating system, or hardware.
node: v12.20.0
npm: 6.14.10
ubuntu: 18
symbol-cli: v0.22.0

**Comment by AlexanderC** [comment]
Same issue here, `symbol-cli` is missing `dist/` folder...

**Comment by fboucquez** [comment]
Hi guys, can you try 'npm install -g symbol-cli@alpha'. This bug should be fixed. I'll release it next

**Comment by joarrries** [comment]
'npm install -g symbol-cli@alpha' is ok

**Comment by fboucquez** [comment]
Thanks @joarrries , we have released, you can use the regular @latest install
