### ISSUE TITLE
votingkeylink fails (Failure_Core_Invalid_Version)

### ISSUE THREAD

**Issue by GodTanu** [nemtech/symbol-cli#348]
1. Expected behavior and actual behavior.
Voting must be deactivated correctly.

2. Steps to reproduce the problem.
Since I test the Link command in the bootstrap, I wanted to release it. However, there was a problem with the unlink command in the bootstrap, so I tried to unlink it using the CLI. But it failed.

symbol-cli transaction votingkeylink
? Enter your wallet password: … **********
? Enter the public key of the voting key account:  … C2CEB88217024537F4150D952E26176A5CB24A4CAF5C1A72C9925209339AC740
? Select an action: ? Unlink
? Enter the maximum fee (absolute amount): … 1000000
? Select the transaction announce mode: ? normal
? Enter the start point: … 1
? Enter the end point: … 26280

→Failure_Core_Invalid_Version

3. Specifications like the version of the project, operating system, or hardware.
Symbol CLI v0.23.0
Ubuntu 18.04.5 LTS
symbol-bootstrap/0.4.0 linux-x64 node-v14.15.4

**Comment by fboucquez** [comment]
Hi @GodTanu . what's the node url you are using?

**Comment by GodTanu** [comment]
80.209.229.160

**Comment by fboucquez** [comment]
Thanks @GodTanu . It's a bug. I've created the PR.

**Comment by GodTanu** [comment]
Thank you for the quick analysis and response.
