### ISSUE TITLE
Unable to sending voting key link transaction

### ISSUE THREAD

**Issue by cryptoBeliever** [nemtech/symbol-cli#351]
I'm unable to send voting key link transaction. Got error "Failure_Core_Invalid_Version" every time.

symbol-cli transaction votingkeylink     --linked-public-key 4BF143F6B53E240FE90B8D591D29BD4AC03A6AF39DD12E0AC488C29583F4F915     --action Link     --sync
? Enter your wallet password: › (node:160199) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:160199) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:160199) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
✔ Enter your wallet password: … *********
✔ Enter the maximum fee (absolute amount): … 1000000
✔ Select the transaction announce mode: › normal
✔ Enter the start point: … 47
✔ Enter the end point: … 1000

**Comment by fboucquez** [comment]
Hi @cryptoBeliever 

We have just released the fix. Please try version 0.23.1

https://github.com/nemtech/symbol-cli/releases/tag/v0.23.1
